package tokens

// NewDefaultTokenizer creates a default tokenizer for use in the project.
// It is configured to support all scripts in common use today.
//
// In case the default configuration changes, any saved data that depends on
// this should be saved with the tokenizer configuration used to create it.
func NewDefaultTokenizer() Analyzer {
	tokenizer := Smart{}
	tokenizer.SetAnalyzers("Adlam", []Analyzer{UAX29{}, NFKC{}, Lowercase{}})
	tokenizer.SetAnalyzers("Ahom", []Analyzer{UAX29{}, NFKC{}, NGram{MinN: 2, MaxN: 3}})
	tokenizer.SetAnalyzers("Arabic", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Armenian", []Analyzer{UAX29{}, NFKC{}, Lowercase{}})
	tokenizer.SetAnalyzers("Balinese", []Analyzer{UAX29{}, NFKC{}, NGram{MinN: 2, MaxN: 3}})
	tokenizer.SetAnalyzers("Batak", []Analyzer{UAX29{}, NFKC{}, NGram{MinN: 2, MaxN: 3}})
	tokenizer.SetAnalyzers("Bengali", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Bopomofo", []Analyzer{UAX29{}, NFKC{}, NGram{MinN: 2, MaxN: 3}})
	tokenizer.SetAnalyzers("Braille", []Analyzer{UAX29{}, NFKC{}, NGram{MinN: 2, MaxN: 3}})
	tokenizer.SetAnalyzers("Buginese", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Buhid", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Canadian_Aboriginal", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Chakma", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Cham", []Analyzer{UAX29{}, NFKC{}, NGram{MinN: 2, MaxN: 3}})
	tokenizer.SetAnalyzers("Cherokee", []Analyzer{UAX29{}, NFKC{}, Lowercase{}})
	tokenizer.SetAnalyzers("Cyrillic", []Analyzer{UAX29{}, NFKC{}, Lowercase{}})
	tokenizer.SetAnalyzers("Devanagari", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Duployan", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Ethiopic", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Georgian", []Analyzer{UAX29{}, NFKC{}, Lowercase{}})
	tokenizer.SetAnalyzers("Grantha", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Greek", []Analyzer{UAX29{}, NFKC{}, Lowercase{}})
	tokenizer.SetAnalyzers("Gujarati", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Gunjala_Gondi", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Gurmukhi", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Han", []Analyzer{UAX29{}, NFKC{}, NGram{MinN: 1, MaxN: 2}})
	tokenizer.SetAnalyzers("Hangul", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Hanifi_Rohingya", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Hanunoo", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Hebrew", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Hiragana", []Analyzer{UAX29{}, NFKC{}, NGram{MinN: 2, MaxN: 3}})
	tokenizer.SetAnalyzers("Javanese", []Analyzer{UAX29{}, NFKC{}, NGram{MinN: 2, MaxN: 3}})
	tokenizer.SetAnalyzers("Kannada", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Katakana", []Analyzer{UAX29{}, NFKC{}, NGram{MinN: 2, MaxN: 3}})
	tokenizer.SetAnalyzers("Kayah_Li", []Analyzer{UAX29{}, NFKC{}, NGram{MinN: 2, MaxN: 3}})
	tokenizer.SetAnalyzers("Khmer", []Analyzer{UAX29{}, NFKC{}, NGram{MinN: 2, MaxN: 3}})
	tokenizer.SetAnalyzers("Khojki", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Lao", []Analyzer{UAX29{}, NFKC{}, NGram{MinN: 2, MaxN: 3}})
	tokenizer.SetAnalyzers("Latin", []Analyzer{UAX29{}, NFKC{}, Lowercase{}})
	tokenizer.SetAnalyzers("Lepcha", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Limbu", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Lisu", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Malayalam", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Mandaic", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Masaram_Gondi", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Medefaidrin", []Analyzer{UAX29{}, NFKC{}, Lowercase{}})
	tokenizer.SetAnalyzers("Meetei_Mayek", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Mende_Kikakui", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Miao", []Analyzer{UAX29{}, NFKC{}, NGram{MinN: 2, MaxN: 3}})
	tokenizer.SetAnalyzers("Modi", []Analyzer{UAX29{}, NFKC{}, Lowercase{}})
	tokenizer.SetAnalyzers("Mongolian", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Mro", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Myanmar", []Analyzer{UAX29{}, NFKC{}, NGram{MinN: 2, MaxN: 3}})
	tokenizer.SetAnalyzers("Nag_Mundari", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("New_Tai_Lue", []Analyzer{UAX29{}, NFKC{}, NGram{MinN: 2, MaxN: 3}})
	tokenizer.SetAnalyzers("Newa", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Nko", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Nushu", []Analyzer{UAX29{}, NFKC{}, NGram{MinN: 2, MaxN: 3}})
	tokenizer.SetAnalyzers("Nyiakeng_Puachue_Hmong", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Ol_Chiki", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Old_Hungarian", []Analyzer{UAX29{}, NFKC{}, Lowercase{}})
	tokenizer.SetAnalyzers("Oriya", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Osage", []Analyzer{UAX29{}, NFKC{}, Lowercase{}})
	tokenizer.SetAnalyzers("Pahawh_Hmong", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Pau_Cin_Hau", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Rejang", []Analyzer{UAX29{}, NFKC{}, NGram{MinN: 2, MaxN: 3}})
	tokenizer.SetAnalyzers("Samaritan", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Saurashtra", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Shavian", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Siddham", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("SignWriting", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Sinhala", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Sogdian", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Sora_Sompeng", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Sundanese", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Syloti_Nagri", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Syriac", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Tagalog", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Tagbanwa", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Tai_Le", []Analyzer{UAX29{}, NFKC{}, NGram{MinN: 2, MaxN: 3}})
	tokenizer.SetAnalyzers("Tai_Tham", []Analyzer{UAX29{}, NFKC{}, NGram{MinN: 2, MaxN: 3}})
	tokenizer.SetAnalyzers("Tai_Viet", []Analyzer{UAX29{}, NFKC{}, NGram{MinN: 2, MaxN: 3}})
	tokenizer.SetAnalyzers("Tamil", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Tangsa", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Telugu", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Thaana", []Analyzer{UAX29{}, NFKC{}, Lowercase{}})
	tokenizer.SetAnalyzers("Thai", []Analyzer{UAX29{}, NFKC{}, NGram{MinN: 2, MaxN: 3}})
	tokenizer.SetAnalyzers("Tibetan", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Tifinagh", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Tirhuta", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Toto", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Vai", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Wancho", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Warang_Citi", []Analyzer{UAX29{}, NFKC{}, Lowercase{}})
	tokenizer.SetAnalyzers("Yezidi", []Analyzer{UAX29{}, NFKC{}})
	tokenizer.SetAnalyzers("Yi", []Analyzer{UAX29{}, NFKC{}, NGram{MinN: 1, MaxN: 2}})
	return &tokenizer
}
