package main

import (
	"context"
	"errors"
	"net/http"
	"net/http/httptest"
	"reflect"
	"testing"
	"testing/fstest"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/subtributary/musings/internal/localization"
	"github.com/subtributary/musings/internal/templates"
)

// This file was generated by Codex and reviewed by a human.
//
// I see several flaws in the AI's generated code, but this is a test file and
// some tests are better than no tests.  Overall I think that the AI did a good
// job of adding value to the project here.
//
// The "view.go" file is complicated, but it is hard to pull it into its
// components since the file is mostly just assembling components that are
// already pulled out.  With limited options to improve the clarity of the
// source code there, the scope of tests for the file remains wide.
//
// If the "view.go" file is cleaned up in the future, then there is less of an
// argument to use AI to generate its test file, and I recommend inverting how
// this file was made: created by human and reviewed by AI.

var (
	viewTestEn = localization.Locale{
		Tag:         "en",
		NativeName:  "English",
		Direction:   "ltr",
		WritingMode: "horizontal-tb",
	}
	viewTestAr = localization.Locale{
		Tag:         "ar",
		NativeName:  "Arabic",
		Direction:   "rtl",
		WritingMode: "horizontal-tb",
	}
)

func TestViewFactoryCreate_NoConfiguredLocales(t *testing.T) {
	t.Parallel()

	f := newTestViewFactory(t, nil, nil)
	req := newTestRequest("/")

	view, err := f.Create(req, "page")
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}

	if len(view.model.LocaleOptions) != 0 {
		t.Fatalf("LocaleOptions length = %d, want 0", len(view.model.LocaleOptions))
	}

	wantLocale := LocaleOption{
		Locale:    localization.UndLocale,
		IsCurrent: true,
		URL:       "/",
	}
	if view.model.Locale != wantLocale {
		t.Errorf("Locale = %#v, want %#v", view.model.Locale, wantLocale)
	}

	if view.model.Translations != nil {
		t.Errorf("Translations = %#v, want nil", view.model.Translations)
	}
}

func TestViewFactoryCreate_ConfiguredLocales(t *testing.T) {
	t.Parallel()

	translations := localization.Store{
		"en": localization.Translations{"title": "Musings"},
		"ar": localization.Translations{"title": "Reflections"},
	}
	f := newTestViewFactory(t, []localization.Locale{viewTestEn, viewTestAr}, translations)
	req := newLocalizedTestRequest(t, []localization.Locale{viewTestEn, viewTestAr}, "/ar/posts", "/posts")

	view, err := f.Create(req, "page")
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}

	wantOptions := []LocaleOption{
		{
			Locale:    viewTestEn,
			IsCurrent: false,
			URL:       "/en/posts",
		},
		{
			Locale:    viewTestAr,
			IsCurrent: true,
			URL:       "/ar/posts",
		},
	}
	if !reflect.DeepEqual(view.model.LocaleOptions, wantOptions) {
		t.Errorf("LocaleOptions = %#v, want %#v", view.model.LocaleOptions, wantOptions)
	}

	if view.model.Locale != wantOptions[1] {
		t.Errorf("Locale = %#v, want %#v", view.model.Locale, wantOptions[1])
	}

	if !reflect.DeepEqual(view.model.Translations, translations["ar"]) {
		t.Errorf("Translations = %#v, want %#v", view.model.Translations, translations["ar"])
	}
}

func TestViewFactoryCreate_ConfiguredLocalesRootPath(t *testing.T) {
	t.Parallel()

	locales := []localization.Locale{viewTestEn, viewTestAr}
	f := newTestViewFactory(t, locales, nil)
	req := newLocalizedTestRequest(t, locales, "/en", "/")

	view, err := f.Create(req, "page")
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}

	wantURLs := []string{"/en/", "/ar/"}
	for i, want := range wantURLs {
		if got := view.model.LocaleOptions[i].URL; got != want {
			t.Errorf("LocaleOptions[%d].URL = %q, want %q", i, got, want)
		}
	}
}

func TestViewFactoryCreate_MissingTranslationForCurrentLocale(t *testing.T) {
	t.Parallel()

	locales := []localization.Locale{viewTestEn, viewTestAr}
	f := newTestViewFactory(t, locales, localization.Store{
		"en": localization.Translations{"title": "Musings"},
	})
	req := newLocalizedTestRequest(t, locales, "/ar/posts", "/posts")

	view, err := f.Create(req, "page")
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}

	if view.model.Translations != nil {
		t.Errorf("Translations = %#v, want nil", view.model.Translations)
	}
}

func TestViewFactoryCreate_Options(t *testing.T) {
	t.Parallel()

	f := newTestViewFactory(t, nil, nil)
	req := newTestRequest("/")
	dataModified := time.Date(2026, 1, 2, 3, 4, 5, 0, time.UTC)
	data := struct{ Title string }{Title: "A post"}

	view, err := f.Create(req, "page",
		WithData(data),
		WithDataModified(dataModified),
	)
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}

	if view.model.Data != data {
		t.Errorf("Data = %#v, want %#v", view.model.Data, data)
	}
	if !view.modified.Equal(dataModified) {
		t.Errorf("modified = %v, want %v", view.modified, dataModified)
	}
}

func TestViewFactoryCreate_WithDataModifiedBeforeTemplate(t *testing.T) {
	t.Parallel()

	f := newTestViewFactory(t, nil, nil)
	req := newTestRequest("/")
	beforeTemplate := time.Date(2025, 12, 31, 23, 59, 59, 0, time.UTC)
	wantModified := time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)

	view, err := f.Create(req, "page", WithDataModified(beforeTemplate))
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}

	if !view.modified.Equal(wantModified) {
		t.Errorf("modified = %v, want %v", view.modified, wantModified)
	}
}

func TestViewFactoryCreate_OptionError(t *testing.T) {
	t.Parallel()

	f := newTestViewFactory(t, nil, nil)
	req := newTestRequest("/")
	wantErr := errors.New("bad option")

	_, err := f.Create(req, "page", func(*View) error {
		return wantErr
	})

	if !errors.Is(err, wantErr) {
		t.Fatalf("Create() error = %v, want %v", err, wantErr)
	}
}

func TestViewFactoryCreate_TemplateLookupError(t *testing.T) {
	t.Parallel()

	f := newTestViewFactory(t, nil, nil)
	req := newTestRequest("/")

	_, err := f.Create(req, "missing")
	if err == nil {
		t.Fatal("Create() error = nil, want template lookup error")
	}
}

func TestViewServe(t *testing.T) {
	t.Parallel()

	f := newTestViewFactory(t, nil, nil)
	req := newTestRequest("/")
	view, err := f.Create(req, "page", WithData("served"))
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}

	rec := httptest.NewRecorder()
	if err := view.Serve(rec); err != nil {
		t.Fatalf("Serve() error = %v", err)
	}

	if got := rec.Header().Get("Content-Type"); got != "text/html; charset=utf-8" {
		t.Errorf("Content-Type = %q, want %q", got, "text/html; charset=utf-8")
	}

	wantModified := time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC).Format(http.TimeFormat)
	if got := rec.Header().Get("Last-Modified"); got != wantModified {
		t.Errorf("Last-Modified = %q, want %q", got, wantModified)
	}

	if got := rec.Body.String(); got != "served" {
		t.Errorf("body = %q, want %q", got, "served")
	}
}

func newTestViewFactory(t *testing.T, locales []localization.Locale, translations localization.Store) *ViewFactory {
	t.Helper()

	store := templates.NewCachedStore()
	err := store.LoadFS(fstest.MapFS{
		"page.gohtml": {
			Data:    []byte(`{{.Data}}`),
			ModTime: time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC),
		},
	})
	if err != nil {
		t.Fatalf("LoadFS() error = %v", err)
	}

	return &ViewFactory{
		locales:       locales,
		templateStore: store,
		translations:  translations,
	}
}

func newTestRequest(routePath string) *http.Request {
	req := httptest.NewRequest(http.MethodGet, routePath, nil)
	return withRoutePath(req, routePath)
}

func newLocalizedTestRequest(t *testing.T, locales []localization.Locale, reqPath string, routePath string) *http.Request {
	t.Helper()

	req := withRoutePath(httptest.NewRequest(http.MethodGet, reqPath, nil), routePath)
	rec := httptest.NewRecorder()
	localized, ok := localization.NewLocalizedRouteMiddleware(locales).Handle(rec, req)
	if !ok {
		t.Fatalf("localized route was not accepted: status %d, location %q", rec.Code, rec.Header().Get("Location"))
	}
	return localized
}

func withRoutePath(req *http.Request, routePath string) *http.Request {
	chiCtx := chi.NewRouteContext()
	chiCtx.URLParams.Add("*", routePath)
	ctx := context.WithValue(req.Context(), chi.RouteCtxKey, chiCtx)
	return req.WithContext(ctx)
}
